spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/reggie?characterEncoding=utf-8&&useSSL=false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    在映射实体或属性中,将数据库中表名和字段名中的下划线去掉,按照驼峰命名来
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: assign_id

reggie:
  path: D:\wendang\-\
